name: annonars-import
description: Run "annonars clinvar-minimal import"

inputs:
  publish-artifacts:
    default: "false"
    description: "Whether to publish artifacts to the named release"
  release-name:
    description: "The name of the release to publish artifacts to"
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}

    - name: Get ClinVar version
      id: get-clinvar
      run: echo "clinvar-release=$(cat clinvar-release.txt || echo 00-latest_weekly)" >> $GITHUB_OUTPUT
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}

    - name: Check cache annonars-import output
      id: check-cache-annonars-import-output
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/${{ matrix.genome_release }}/seqvar/annonars-import
        key: annonars-import-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-${{ matrix.genome_release }}
        lookup-only: true

    - name: Install Conda environment
      if: steps.check-cache-annonars-import-output.outputs.cache-hit != 'true'
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-environment: true
        environment-name: annonars-data-clinvar
        condarc: |
          channels:
            - conda-forge
            - bioconda
            - defaults
        create-args: >-
          samtools
          htslib
          python=${{ env.PYTHON_VERSION }}
          annonars=${{ env.ANNONARS_VERSION }}
          clinvar-tsv=${{ env.CLINVAR_TSV_VERSION }}

    - name: Cache annonars import output
      # Enable this if cache was not hit (we need to rebuild) or we publish and
      # then need the cache in any case.
      if: |
        (steps.check-cache-annonars-import-output.outputs.cache-hit != 'true') ||
        (inputs.publish-artifacts == 'true')
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/${{ matrix.genome_release }}/seqvar/annonars-import
        key: annonars-import-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-${{ matrix.genome_release }}

    - name: Retrieve merge seqvars output
      if: steps.check-cache-annonars-import-output.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/${{ matrix.genome_release }}/seqvar/merged
        key: merge-seqvars-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-${{ matrix.genome_release }}
        fail-on-cache-miss: true

    - name: Run the annonars import
      if: steps.check-cache-annonars-import-output.outputs.cache-hit != 'true'
      run: bash .github/actions/annonars-import/run.sh
      env:
        GENOME_RELEASE: "${{ matrix.genome_release }}"
        CLINVAR_RELEASE: "${{ steps.get-clinvar.outputs.clinvar-release }}"
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}

    - name: Publish artifacts
      if: inputs.publish-artifacts == 'true'
      run: |
        set -xv

        genome_release=$(echo ${{ matrix.genome_release }} | tr '[:upper:]' '[:lower:]')
        version=$(\
            grep ^dc.identifier \
              ${{ env.OUTPUT_DIR }}/${{ matrix.genome_release }}/seqvar/annonars-import/spec.yaml \
            | rev \
            | cut -d - -f 1 \
            | rev)

        mkdir -p /tmp/for-upload/clinvar-annonars-rocksdb-$genome_release-$version
        rsync -av \
          ${{ env.OUTPUT_DIR }}/${{ matrix.genome_release }}/seqvar/annonars-import/. \
          /tmp/for-upload/clinvar-annonars-rocksdb-$genome_release-$version/.
        ls -lhR /tmp/for-upload/clinvar-annonars-rocksdb-$genome_release-$version
        tar --directory=/tmp/for-upload --create --owner=0:0 --gzip \
          --file /tmp/for-upload/clinvar-annonars-rocksdb-$genome_release-$version.tar.gz \
          clinvar-annonars-rocksdb-$genome_release-$version

        pushd /tmp/for-upload
        sha256sum clinvar-annonars-rocksdb-$genome_release-$version.tar.gz \
        > clinvar-annonars-rocksdb-$genome_release-$version.tar.gz.sha256
        popd

        gh release upload --clobber "clinvar-weekly-${{ inputs.release-name }}" \
          /tmp/for-upload/clinvar-annonars-rocksdb-$genome_release-$version.tar.gz*
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: stdbuf -oL bash -l {0}
