name: convert-clinvar
description: Convert ClinVar XML to TSV

runs:
  using: "composite"
  steps:
    - name: Get ClinVar version
      id: get-clinvar
      run: |
        echo "clinvar-release=$(cat clinvar-release.txt || echo 00-latest_weekly)" >> $GITHUB_OUTPUT
        df -h
        ls -lhR $HOME
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}

    - name: Check cache GRCh37 sequence variant parse_xml output
      id: check-cache-grch37-seqvar-parse-xml-output
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/GRCh37/seqvar/parsed
        key: convert-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-GRCh37-seqvar
        lookup-only: true

    - name: Check cache GRCh37 structural variant parse_xml output
      id: check-cache-grch37-strucvar-parse-xml-output
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/GRCh37/strucvar/parsed
        key: convert-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-GRCh37-strucvar
        lookup-only: true

    - name: Check cache GRCh38 sequence variant parse_xml output
      id: check-cache-grch38-seqvar-parse-xml-output
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/GRCh38/seqvar/parsed
        key: convert-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-GRCh38-seqvar
        lookup-only: true

    - name: Check cache GRCh38 structural variant parse_xml output
      id: check-cache-grch38-strucvar-parse-xml-output
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/GRCh38/strucvar/parsed
        key: convert-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-GRCh38-strucvar
        lookup-only: true

    - name: Install Conda environment
      if: |
        (steps.check-cache-grch37-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch37-strucvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-strucvar-parse-xml-output.outputs.cache-hit != 'true')
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-environment: true
        environment-name: annonars-data-clinvar
        condarc: |
          channels:
            - conda-forge
            - bioconda
            - defaults
        create-args: >-
          samtools
          htslib
          python=${{ env.PYTHON_VERSION }}
          annonars=${{ env.ANNONARS_VERSION }}
          clinvar-tsv=${{ env.CLINVAR_TSV_VERSION }}

    - name: Cache GRCh37 sequence variant parse_xml output
      if: |
        (steps.check-cache-grch37-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch37-strucvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-strucvar-parse-xml-output.outputs.cache-hit != 'true')
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/GRCh37/seqvar/parsed
        key: convert-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-GRCh37-seqvar

    - name: Cache GRCh37 structural variant parse_xml output
      if: |
        (steps.check-cache-grch37-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch37-strucvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-strucvar-parse-xml-output.outputs.cache-hit != 'true')
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/GRCh37/strucvar/parsed
        key: convert-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-GRCh37-strucvar

    - name: Cache GRCh38 sequence variant parse_xml output
      if: |
        (steps.check-cache-grch37-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch37-strucvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-strucvar-parse-xml-output.outputs.cache-hit != 'true')
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/GRCh38/seqvar/parsed
        key: convert-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-GRCh38-seqvar

    - name: Cache GRCh38 structural variant parse_xml output
      if: |
        (steps.check-cache-grch37-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch37-strucvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-strucvar-parse-xml-output.outputs.cache-hit != 'true')
      uses: actions/cache@v3
      with:
        path: ${{ env.OUTPUT_DIR }}/GRCh38/strucvar/parsed
        key: convert-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}-${{ env.CLINVAR_TSV_VERSION }}-${{ env.MAX_RCVS }}-GRCh38-strucvar

    - name: Retrieve cached ClinVar file
      if: |
        (steps.check-cache-grch37-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch37-strucvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-strucvar-parse-xml-output.outputs.cache-hit != 'true')
      uses: actions/cache@v3
      with:
        path: ${{ env.CLINVAR_DIR }}
        key: download-clinvar-${{ env.CACHE_SEED }}-${{ steps.get-clinvar.outputs.clinvar-release }}
        fail-on-cache-miss: true

    - name: Run the xml-to-tsv conversion
      if: |
        (steps.check-cache-grch37-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch37-strucvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-seqvar-parse-xml-output.outputs.cache-hit != 'true') ||
        (steps.check-cache-grch38-strucvar-parse-xml-output.outputs.cache-hit != 'true')
      run: bash .github/actions/convert-clinvar/run.sh
      env:
        CLINVAR_RELEASE: "${{ steps.get-clinvar.outputs.clinvar-release }}"
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}
