name: download-ref
description: Download reference FASTA files

runs:
  using: "composite"
  steps:
    - name: Install Conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-environment: true
        environment-name: annonars-data-clinvar
        condarc: |
          channels:
            - conda-forge
            - bioconda
            - defaults
        create-args: >-
          samtools
          htslib

    - name: Get current date
      id: get-today
      run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}

    - name: Check for cache reference files
      id: check-cache-ref-files
      uses: actions/cache@v3
      with:
        path: ${{ env.REF_DIR }}
        key: download-ref-${{ env.CACHE_SEED }}-${{ steps.get-today.outputs.today }}
        lookup-only: true

    - name: Cache reference files
      if: steps.check-cache-ref-files.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: ${{ env.REF_DIR }}
        key: download-ref-${{ env.CACHE_SEED }}-${{ steps.get-today.outputs.today }}
        lookup-only: true

    - name: Download reference files if necessary
      if: steps.check-cache-ref-files.outputs.cache-hit != 'true'
      run: bash .github/actions/download-ref/run.sh
      # cf. https://github.com/mamba-org/provision-with-micromamba#important
      shell: bash -l {0}
