# Re-useable version of the "main" workflow such that it can be used both
# for pull requests/CI and for creating the release.
on:
  workflow_call:
    inputs:
      release-name:
        type: string
      # Whether to publish artifacts to the named release.
      publish-artifacts:
        type: boolean

# cf. https://github.com/mamba-org/provision-with-micromamba#important
defaults:
  run:
    shell: bash -l {0}

env:
  # Path to directory with reference sequences.
  REF_DIR: /home/runner/work/references
  # Path to the directory with ClinVar download.
  CLINVAR_DIR: /home/runner/work/clinvar
  # Parse to the directory with clinvar-tsv output files.
  OUTPUT_DIR: /home/runner/work/output
  # Python version
  PYTHON_VERSION: "3.10"
  # annonars package version
  ANNONARS_VERSION: "0.12.4"
  # clinvar-tsv package version
  CLINVAR_TSV_VERSION: "0.6.3"
  # Maximal number of RCVs to process.
  MAX_RCVS: 1005

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: khan/pull-request-workflow-cancel@1.0.0
        with:
          workflows: "main.yml"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  # Download-Ref: Download reference sequences
  Download-Ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/download-ref

  # Download-ClinVar: Download "weekly" ClinVar XML file.
  Download-ClinVar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/download-clinvar

  # Convert-ClinVar: Convert ClinVar XML file to TSV.
  Convert-Clinvar:
    runs-on: ubuntu-latest
    needs: Download-ClinVar
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/convert-clinvar

  # Normalize-SeqVars: Normalize small variants.
  Normalize-SeqVars:
    runs-on: ubuntu-latest
    needs:
      - Convert-Clinvar
      - Download-Ref
    strategy:
      matrix:
        genome_release:
          - GRCh37
          - GRCh38
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/normalize-seqvars

  # Sort-SeqVars: Sort small variants.
  Sort-SeqVars:
    runs-on: ubuntu-latest
    needs:
      - Normalize-SeqVars
    strategy:
      matrix:
        genome_release:
          - GRCh37
          - GRCh38
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/sort-seqvars

  # Sort-StrucVars: Sort structural variants.
  Sort-StrucVars:
    runs-on: ubuntu-latest
    needs:
      - Convert-Clinvar
    strategy:
      matrix:
        genome_release:
          - GRCh37
          - GRCh38
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/sort-strucvars

  # Merge-SeqVars: merge sequence variants RCV into VCV records.
  Merge-SeqVars:
    runs-on: ubuntu-latest
    needs:
      - Sort-SeqVars
    strategy:
      matrix:
        genome_release:
          - GRCh37
          - GRCh38
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/merge-seqvars

  # Merge-StrucVars: merge structural variants RCV into VCV records.
  Merge-StrucVars:
    runs-on: ubuntu-latest
    needs:
      - Sort-StrucVars
    strategy:
      matrix:
        genome_release:
          - GRCh37
          - GRCh38
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/merge-seqvars

  # Annonars-Import: Import seqvars into annonars RocksDB
  Annonars-Import:
    runs-on: ubuntu-latest
    needs:
      - Merge-SeqVars
    strategy:
      matrix:
        genome_release:
          - GRCh37
          - GRCh38
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/annonars-import
