name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# cf. https://github.com/mamba-org/provision-with-micromamba#important
defaults:
  run:
    shell: bash -l {0}

env:
  # Path to directory with reference sequences.
  REF_DIR: /home/runner/work/references
  # Path to the directory with ClinVar download.
  CLINVAR_DIR: /home/runner/work/clinvar

jobs:
  # strategy:
  #   matrix:
  #     annonars_version:
  #       - "0.12.4"
  #     clinvar_tsv_version:
  #       - "0.6.2"

  # - name: Install Conda environment
  #   uses: mamba-org/setup-micromamba@v1
  #   with:
  #     cache-environment: true
  #     environment-name: annonars-data-clinvar
  #     condarc: |
  #       channels:
  #         - conda-forge
  #         - bioconda
  #         - defaults
  #     create-args: >-
  #       python=3.10
  #       samtools
  #       htslib
  #       annonars=${{ matrix.annonars_version }}
  #       clinvar-tsv=${{ matrix.clinvar_tsv_version }}

  # Download-Ref: Download reference sequences
  #
  # We will cache them for the current day.
  Download-Ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-environment: true
          environment-name: annonars-data-clinvar
          condarc: |
            channels:
              - conda-forge
              - bioconda
              - defaults
          create-args: >-
            samtools
            htslib

      - name: Get current date
        id: get-today
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache reference files
        uses: actions/cache@v3
        with:
          path: /home/runner/work/references
          key: references-${{ steps.get-today.outputs.today }}

      - name: Download reference files if necessary
        run: bash src/download-refs.sh

  # Download-ClinVar: Download "weekly" ClinVar XML file.
  Download-ClinVar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get clinvar version
        id: get-clinvar
        run: echo "clinvar-release=$(cat clinvar-release.txt || echo 00-latest_weekly)" >> $GITHUB_OUTPUT

      - name: Cache ClinVar files
        uses: actions/cache@v3
        with:
          path: /home/runner/work/clinvar
          key: clinvar-${{ steps.get-clinvar.outputs.clinvar-release }}

      - name: Download reference files if necessary
        run: bash src/download-clinvar.sh
        env:
          CLINVAR_RELEASE: "${{ steps.get-clinvar.outputs.clinvar-release }}"
