name: Release

defaults:
  run:
    # cf. https://github.com/mamba-org/provision-with-micromamba#important
    shell: bash -l {0}


on:
  push:
    branches:
      - main

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    outputs:
      is-release: ${{ steps.check-release.outputs.is-release }}
      release-name: ${{ steps.check-release.outputs.release-name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check whether we are on a release commit
        id: check-release
        run: |
          msg=$(git log -1 --pretty=%B | head -n 1)
          if [[ "$msg" == "chore: update ClinVar release to"* ]]; then
            echo "This is a release commit."
            echo is-release=true >> $GITHUB_ENV
            # The full name of the weekly release, includes the dash after the year.
            echo clinvar-release=$(cat clinvar-release.txt || echo 00-latest_weekly) >> $GITHUB_ENV
            # The release name without the dash after the year.
            echo release-name=$(cat clinvar-release.txt || echo 00-latest_weekly | tr -d '-') >> $GITHUB_ENV
          else
            echo "This is not a release commit."
            echo is-release=false >> $GITHUB_ENV
          fi

      - name: Create release
        if: steps.check-release.outputs.is-release != 'true'
        run: |
          gh release create clinvar-weekly-$RELEASE_NAME --draft=true \
            --title "ClinVar Weekly Release $RELEASE_NAME" \
            --notes "This release was created automatically by GitHub Action in our CI."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.check-release.outputs.release-name }}
          CLINVAR_RELEASE: ${{ steps.check-release.outputs.clinvar-release }}

  Publish-Artifacts:
    needs:
      - Create-Release
    uses: ./.github/workflows/-build-artifacts.yml
    secrets: inherit
    with:
      publish-artifacts: ${{ needs.Create-Release.outputs.is-release }}
      release-name: ${{ needs.Create-Release.outputs.release-name }}

  Publish-Release:
    runs-on: ubuntu-latest
    needs:
      - Publish-Artifacts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mark release as published
        run: |
          gh release edit clinvar-weekly-$RELEASE_NAME --draft=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.check-release.outputs.release-name }}
